import Layout from '@/components/layout'
import Meta from '@/components/meta'
import { HOST } from '@/constants'

export default function Home() {
  return (
    <Layout>
      <Meta
        title="About || Next.js starter"
        desc="Generated by create next app"
        canonical={`${HOST}about`}
      />
      <div className="container">About</div>
    </Layout>
  )
}
